name: 'RPM Build'
description: 'Build RPMs from spec file and upload it as Artifact or Release Asset'
author: 'gsfjohnson'

inputs:
  spec_path:
    description: 'path to the spec file'
    required: true
  keep_debuginfo:
    description: 'keep generated debuginfo package; use boolean true or false without quotes'
    default: false
  preinstall_packages:
    description: 'packages to install beforehand'

outputs:
  srpm_dir:
    description: 'SRPM directory'
  srpm_path:
    description: 'SRPM filepath'
  srpm_name:
    description: 'SRPM filename'
  rpm_dir:
    description: 'RPM directory'
  content_type:
    description: 'Content-type for Upload'

runs:
  using: 'docker'
  image: Dockerfile

branding:
  icon: 'package'
  color: 'red'
