name: 'RPM Build'
description: 'Build RPMs from spec file and upload them as Release Assets'
author: 'gsfjohnson'

inputs:
  spec_path:
    description: 'path to the spec file'
    required: true
  spec_name:
    description: 'rewrite Name: in spec file'
  spec_version:
    description: 'rewrite Version: in spec file'
  redownload_source:
    description: 'create source tar gz from workspace by default, specify true to redownload source'
    default: false
  keep_debuginfo:
    description: 'keep generated debuginfo package; use boolean true or false without quotes'
    default: false
  preinstall_packages:
    description: 'packages to install beforehand'

outputs:
  srpm_dir:
    description: 'Path to the directory with the generated SRPM file.'
  srpm_path:
    description: 'Path to the generated SRPM file.'
  srpm_name:
    description: 'Name of the generated SRPM file.'
  rpm_dir:
    description: 'Path to the directory with the generated RPM file.'
  rpm_path:
    description: 'Path to the generated RPM file.'
  rpm_name:
    description: 'Name of the generated RPM file.'
  content_type:
    description: 'Content-type for the RPM upload.'

runs:
  using: 'docker'
  image: Dockerfile

branding:
  icon: 'package'
  color: 'red'
